log4j.logger.ros=INFO
log4j.logger.ros.roscpp.superdebug=WARN

log4j.logger.ros.moveit=WARN
log4j.logger.ros.moveit_ros_move_group=WARN
log4j.logger.ros.moveit_ros_planning=WARN
log4j.logger.ros.moveit_ros_planning_interface=WARN
log4j.logger.ros.moveit_ros_manipulation=WARN
log4j.logger.ros.moveit_trajectory_processing=WARN
log4j.logger.ros.moveit_robot_model=WARN
log4j.logger.ros.moveit_kinematics_base=WARN
log4j.logger.ros.moveit_core=WARN

log4j.logger.ompl=WARN
log4j.logger.ros.ompl=WARN
